Repository UCLA-Creative-Labs/password, pull requests merged in 2020-11, with the labels that each got.

#18 feat: ghostie level
  src/assets/ghostie-incog.svg
  src/assets/ghostie-reg.svg
  src/assets/ghostie-submit.svg
  src/components/App.tsx
  src/components/Levels/Ghostie.tsx
  src/components/Levels/Level2.tsx
  src/components/Levels/index.tsx
  src/components/styles/Ghostie.scss
  src/components/styles/Header.scss
  src/utils/Utils.tsx
Labels: feature

#20 feat: spooky maze
  src/assets/JLevelAssets/back.png
  src/assets/JLevelAssets/doorf.png
  src/assets/JLevelAssets/doorl.png
  src/assets/JLevelAssets/doorr.png
  src/assets/JLevelAssets/ghost.png
  src/assets/JLevelAssets/halll.png
  src/assets/JLevelAssets/hallr.png
  src/assets/JLevelAssets/liminalback.png
  src/assets/JLevelAssets/liminaldoor.png
  src/assets/JLevelAssets/liminaldoorr.png
  src/assets/JLevelAssets/liminaldoorway.png
  src/assets/JLevelAssets/liminaldoorwayr.png
  src/assets/JLevelAssets/rhall.png
  src/components/Levels/TypeRacerLevel.tsx
  src/components/Levels/index.tsx
  src/components/Levels/jlevel.tsx
  src/components/styles/JLevel.scss
Labels: feature

#25 chore: some styling + changing name to spooknt
  CONTRIBUTING.md
  README.md
  public/index.html
  src/components/404.tsx
  src/components/App.tsx
  src/components/Home.tsx
  src/components/styles/App.scss
Labels: chore

#26 fix: wtf merfiyio.. why u like this
  CODE_OF_CONDUCT.md
  README.md
Labels: bug

#27 fix: ghostie bug that prevent firebase update because of refresh
  src/components/Levels/Ghostie.tsx
Labels: bug

#29 chore: cleaned up the repo
  src/components/404.tsx
  src/components/App.tsx
  src/components/Construction.tsx
  src/components/Leaderboard.tsx
  src/components/Levels/BobaShop.tsx
  src/components/Levels/Ghostie.tsx
  src/components/Levels/index.tsx
  src/components/styles/App.scss
  src/global.scss
  src/utils/Utils.tsx
  src/utils/firebase.ts
Labels: chore
