Repository UCLA-Creative-Labs/password, pull requests merged in 2020-10, with the labels that each got.

#7 refactor: create _Firebase class and ReactContextProvider for global Firebase state
  src/components/App.tsx
  src/components/Header.tsx
  src/utils/firebase.ts
Labels: refactor

#9 feat: basic get/update crud operations
  src/utils/firebase.ts
Labels: feature

#10 docs: changed 'master' to 'main' in README.md
  README.md
Labels: docs

#8 feat: level wrapper component
  src/components/App.tsx
  src/components/Header.tsx
  src/components/Level1.tsx
  src/components/Level2.tsx
  src/components/Levels/Level1.tsx
  src/components/Levels/Level2.tsx
  src/components/Levels/index.tsx
  src/utils/firebase.ts
Labels: feature

#13 fix: add redirects to allow for levels
  netlify.toml
Labels: bug

#15 docs: Added instructions for Level wrapper in DESIGN_GUIDELINES
  DESIGN_GUIDELINES.md
Labels: docs

#14 feat: add 404 component + switch
  src/components/404.tsx
  src/components/App.tsx
Labels: feature

#16 fix: allow for single child of Level component
  src/components/Levels/index.tsx
Labels: bug

#19 feat: admin functionality
  src/components/Levels/index.tsx
  src/utils/firebase.ts
Labels: feature

#21 fix: host to localhost
  package.json
Labels: bug

#11 feat: Create RaceTypeLevel
  package.json
  src/assets/typeracercar.jpg
  src/components/App.tsx
  src/components/Levels/Level2.tsx
  src/components/Levels/TypeRacerLevel.tsx
  src/components/Levels/index.tsx
  src/components/styles/TypeRacerLevel.scss
  yarn.lock
Labels: feature
